### ISSUE TITLE
If-None-Match use cause exceptions and data loss or GTE 

### ISSUE THREAD

**Issue by bvdh** [FHIR/fhir-candle#18]
When accessing FhirCandle from a browser I ran into the issue that the `If-None-Match` header is set. 

Such behavior is supported (see https://www.hl7.org/fhir/http.html#cread).

This causes an error in creation of the response body as the dotnet library seams to have issues with adding a response body to a response with HttpStatusCode.NotModified. An empty response also is an issue for the application as it is expecting data and not getting any. I'm reading the data using fhirclient.js, not sure whether it can disable it.

The exception I'm getting is:
> Connection id "0HN834R99BCFH", Request id "0HN834R99BCFH:00000001": An unhandled exception was thrown by the application.
      System.InvalidOperationException: Writing to the response body is invalid for responses with status code 304.
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.Advance(Int32 bytes)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponsePipeWriter.Advance(Int32 bytes)
         at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.Write(HttpResponse response, String text, Encoding encoding)
         at Microsoft.AspNetCore.Http.HttpResponseWritingExtensions.WriteAsync(HttpResponse response, String text, Encoding encoding, CancellationToken cancellationToken)
         at fhir.candle.Controllers.FhirController.AddFhirResponse(HttpResponse response, String prefer, Boolean success, FhirResponseContext opResponse) in C:\Data\github-philips\fhir-dicom\src\DicomOnFhir.App.FhirCandle\Controllers\FhirController.cs:line 214
         at fhir.candle.Controllers.FhirController.GetResourceInstance(String storeName, String resourceName, String id, String format, String summary, String pretty, String ifMatch, String ifModifiedSince, String ifNoneMatch, String authHeader) in C:\Data\github-philips\fhir-dicom\src\DicomOnFhir.App.FhirCandle\Controllers\FhirController.cs:line 449

Disabling this behavior by removing line 2034-2042 in VersionFhirStore,cs, disables this behavior and fixes the issue.

I suggest to make support of 'ifNoneMatch' optional (and return an empty response) and to add a configuration variable for it or to remove the functionality.

**Comment by GinoCanessa** [comment]
Hi @bvdh , I am reviewing the PR now.  To be clear, this is for a request that is made with an `If-Non-Match` header but is *not* able to parse the defined response based on that header?

**Comment by bvdh** [comment]
The code receives a If-None-Match call, sees that the version of the current resource and the Etag match, creates a response with 304 Modified, and tries to add the resource content. 
So far as I understand the latter step causes the exception; a 304 response is not supposed to have a body.

**Comment by GinoCanessa** [comment]
Ah, missed that. In that case, we should not have a setting at all and just fix the response.  Do you want me to modify the PR to match? I do not want to lose your other changes.

**Comment by GinoCanessa** [comment]
@bvdh - I merged your PR, thanks!  Also, in my current branch (planning to merge later today) I have added a fix so that a 304 response does not include a body.  If that works for you, I will remove the configuration option that you added.  Otherwise, please let me know so that I can keep it, though I will likely swap the default.

Thanks again!

**Comment by GinoCanessa** [comment]
Assume the changes in PR #22 are sufficient.  If there are further problems, please open a new issue.
